//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.playqd.mediaserver.api.soap.data;

import jakarta.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Browse", namespace = "", propOrder = {
    "objectID",
    "browseFlag",
    "filter",
    "startingIndex",
    "requestedCount",
    "sortCriteria"
})
public class Browse {

    @XmlElement(name = "ObjectID", required = true)
    protected String objectID;

    @XmlElement(name = "BrowseFlag", required = true)
    @XmlSchemaType(name = "string")
    protected BrowseFlag browseFlag;

    @XmlElement(name = "Filter", required = true)
    protected String filter;

    @XmlElement(name = "StartingIndex")
    protected int startingIndex;

    @XmlElement(name = "RequestedCount")
    protected int requestedCount;

    @XmlElement(name = "SortCriteria", required = true)
    protected String sortCriteria;

    /**
     * Gets the value of the objectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectID() {
        return objectID;
    }

    /**
     * Sets the value of the objectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectID(String value) {
        this.objectID = value;
    }

    /**
     * Gets the value of the browseFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BrowseFlag }
     *     
     */
    public BrowseFlag getBrowseFlag() {
        return browseFlag;
    }

    /**
     * Sets the value of the browseFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrowseFlag }
     *     
     */
    public void setBrowseFlag(BrowseFlag value) {
        this.browseFlag = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilter(String value) {
        this.filter = value;
    }

    /**
     * Gets the value of the startingIndex property.
     * 
     */
    public int getStartingIndex() {
        return startingIndex;
    }

    /**
     * Sets the value of the startingIndex property.
     * 
     */
    public void setStartingIndex(int value) {
        this.startingIndex = value;
    }

    /**
     * Gets the value of the requestedCount property.
     * 
     */
    public int getRequestedCount() {
        return requestedCount;
    }

    /**
     * Sets the value of the requestedCount property.
     * 
     */
    public void setRequestedCount(int value) {
        this.requestedCount = value;
    }

    /**
     * Gets the value of the sortCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortCriteria() {
        return sortCriteria;
    }

    /**
     * Sets the value of the sortCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortCriteria(String value) {
        this.sortCriteria = value;
    }

}
