//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.playqd.upnp.api.soap.data;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Body">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Browse" type="{http://www.playqd.io/webservice/model/xsd/upnp}Browse"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "browse"
})
public class Body {

    @XmlElement(name = "Browse", required = true, namespace = "urn:schemas-upnp-org:service:ContentDirectory:1")
    protected Browse browse;

    /**
     * Gets the value of the browse property.
     * 
     * @return
     *     possible object is
     *     {@link Browse }
     *     
     */
    public Browse getBrowse() {
        return browse;
    }

    /**
     * Sets the value of the browse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Browse }
     *     
     */
    public void setBrowse(Browse value) {
        this.browse = value;
    }

}
